Productos/routes.py
from flask import Blueprint, render_template,flash
from flask_security import login_required, current_user
from flask_security.decorators import roles_required
import logging
from forms import UseForm,ProductoForm
from model import Producto,db, Pedido
from flask import request
from flask import redirect, render_template, url_for
import base64

# productos = Blueprint('productos', _name_, url_prefix='/productos')
logger = logging.getLogger(__name__)
logger.setLevel(logging.INFO)
formatter = logging.Formatter('%(asctime)s - %(levelname)s - %(message)s')
file_handler = logging.FileHandler('app.log')
file_handler.setFormatter(formatter)
logger.addHandler(file_handler)

productos = Blueprint('productos',__name__)

@productos.route('/profile')
@login_required
#@roles_required('admin','user')
def profile():
    create_forms=UseForm(request.form)
    productosAll=Producto.query.all()
    for p in productosAll:
        print(p.nombre)
    if current_user.roles[0].name=="admin":
        admin=True
        return render_template('admin/listaProductos.html',form=create_forms,productos=productosAll,admin=admin)
    else:
        admin=False
        return render_template('user/profile.html',name=current_user.name,admin=admin)    

@productos.route('/productosMenu')
@login_required
@roles_required('user')
def productosMenu():
        productosAll=Producto.query.all()
        return render_template('user/productos.html',productos=productosAll)

@productos.route("/agregarProducto",methods=['GET','POST'])
def agregarProducto():
    create_forms=ProductoForm(request.form)
    if request.method=='POST':
        try:
            imagenR= request.files['image']
            imagen = base64.b64encode(imagenR.read())
            product= Producto(
                 nombre = create_forms.nombre.data,
                 descripcion = create_forms.descripcion.data,
                 stock = create_forms.stock.data,
                 altura = create_forms.altura.data,
                 ancho = create_forms.ancho.data,
                 largo = create_forms.largo.data,
                 image = imagen,
                 subtotal = create_forms.subtotal.data,
                 total = create_forms.total.data)
            db.session.add(product)
            db.session.commit()
            logger.info('Producto agregado por'+current_user.name+' con id '+str(current_user.id))
            return redirect(url_for('productos.profile'))
        except Exception as e:  
            logger.error(str(e) + ' Error al agregar producto por '+current_user.name+' con id '+str(current_user.id))
            flash('Error al agregar producto')
    return render_template('admin/agregar.html',form=create_forms)


@productos.route("/modificarProducto",methods=['GET','POST'])
def modificarProducto():
    create_forms=ProductoForm(request.form)
    if request.method=='GET':
        id=request.args.get('id')
        product= db.session.query(Producto).filter(Producto.id==id).first()
        create_forms.id.data=product.id
        create_forms.nombre.data= product.nombre
        create_forms.descripcion.data= product.descripcion
        create_forms.stock.data= product.stock
        create_forms.altura.data= product.altura
        create_forms.ancho.data= product.ancho
        create_forms.largo.data= product.largo
        create_forms.subtotal.data= product.subtotal
        create_forms.total.data= product.total
        create_forms.image.data= product.image
        """create_forms.id.data=product.id
        create_forms.nombreProducto.data= product.nombreProducto
        create_forms.precio.data= product.precio
        create_forms.marca.data= product.marca
        create_forms.cantidad.data= product.cantidad"""


    if request.method=='POST':
        try:
            imagenR= request.files['image']
            imagen = base64.b64encode(imagenR.read())
            print(imagen)
            id=create_forms.id.data
            product= db.session.query(Producto).filter(Producto.id==id).first()
            product.id=create_forms.id.data
            product.nombre=create_forms.nombre.data
            product.descripcion=create_forms.descripcion.data
            product.stock=create_forms.stock.data
            product.altura=create_forms.altura.data
            product.ancho=create_forms.ancho.data
            product.largo=create_forms.largo.data
            product.subtotal=create_forms.subtotal.data
            product.total=create_forms.total.data
            db.session.add(product)
            db.session.commit()
            logger.info('Producto modificado por '+current_user.name+' con id '+str(current_user.id))
            return redirect(url_for('productos.profile'))
        except Exception as e:    
            logger.error(e)

    return render_template('admin/modificar.html',form=create_forms)

@productos.route("/eliminarProducto")
def eliminarProducto():
        id=request.args.get('id')
        product= db.session.query(Producto).filter(Producto.id==id).first()
        db.session.delete(product)
        db.session.commit()
        logger.info('Producto eliminado por '+current_user.name+' con id '+str(current_user.id))

        # flash("Se ha eliminado el producto")
        return redirect(url_for('productos.profile'))

informativo/routes.py
from flask import Blueprint, flash, render_template

from model import Producto


informativo = Blueprint('informativo', __name__)
#Definir la ruta de la pagina informativa sobre nosotros
@informativo.route('/sobre_nosotros', methods=['GET', 'POST'])
def sobre_nosotros():
    return render_template('sobre_nosotros.html')

#Definir la ruta de la pagina informativa contacto
@informativo.route('/contacto', methods=['GET', 'POST'])
def contacto():
    return render_template('contacto.html')

#definir la ruta de la pagina de carrousel

@informativo.route('/carrousel', methods=['GET', 'POST'])
def carrousel():
    productosAll = Producto.query.all()
    return render_template('carrousel.html',informativo=productosAll)

#Definir la ruta para redirigir a la pagina de security.login
@informativo.route('/login', methods=['GET', 'POST'])
def login():
    flash('Por favor, inicie sesión para acceder a esta página')
    return render_template('security/login.html')

#Definir la ruta para la pagina de ver detalle solo informativo del producto
@informativo.route('/ver_detalle/<int:id>', methods=['GET', 'POST'])
def ver_detalle(id):
    producto = Producto.query.get(id)
    return render_template('ver_detalle.html', producto=producto)

templates/_macros.html
{% macro render_input(name,placeholder,id,type="text") %}
<div class="control-group">
    <label class="control-label" for="{{name}}">{{placeholder}}</label>
    <div class="controls">
        <input type="{{type}}" name="{{name}}" id="{{id}}" placeholder="{{placeholder}}" value="">
    </div>
</div>
{%endmacro%}

{%macro render_field(field)%}
<div class="input-group">
     <div class="form-control">
          {{field.label}} 
          {{field(**kwargs) | safe}}
     </div>
</div>
{% if field.errors %}
     <ul>
          {% for error in field.errors %}
               <li style="color: red;">{{error}}</li>
          {% endfor %}
     </ul>
{% endif %}
{%endmacro%}



{%macro renderNuevo_field(field)%}
<div class="form-group">
     <div class="form-control">
          {{field.label}} 
          {{field(**kwargs) | safe}}
     </div>
</div>
{% if field.errors %}
     <ul>
          {% for error in field.errors %}
               <li style="color: red;">{{error}}</li>
          {% endfor %}
     </ul>
{% endif %}
{%endmacro%}

templates/base.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>InflabExpress</title>
  <link rel="icon" href="../../static/img/logo.png">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>


  <link href="https://cdn.datatables.net/v/dt/dt-1.13.4/datatables.min.css" rel="stylesheet" />


  <link rel="stylesheet" href="../static/css/login.css">
  <!-- <script src="../static/jquery/jquery-3.6.4.min.js" ></script> -->
  <script src="../static/js/productos.js"></script>



<link rel="stylesheet" type="text/css" href="https://pixinvent.com/stack-responsive-bootstrap-4-admin-template/app-assets/css/bootstrap-extended.min.css">
<link rel="stylesheet" type="text/css" href="https://pixinvent.com/stack-responsive-bootstrap-4-admin-template/app-assets/fonts/simple-line-icons/style.min.css">
<link rel="stylesheet" type="text/css" href="https://pixinvent.com/stack-responsive-bootstrap-4-admin-template/app-assets/css/colors.min.css">
<link rel="stylesheet" type="text/css" href="https://pixinvent.com/stack-responsive-bootstrap-4-admin-template/app-assets/css/bootstrap.min.css">
<link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">




</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #4abaa5;">
    <a class="navbar-brand text-white" href="#">InflabExpress</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
      aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        {% if (not current_user.is_authenticated) %}

        <li class="nav-item active">
          <a href="{{ url_for('productos.index') }}" class="nav-link font-weight-bold text-white">
            ¿Quienes Somos?
          </a>
        </li>
        {% endif %}

        {% if current_user.is_authenticated %}
        {% if admin %}

        <li class="nav-item">
          <a href="{{ url_for('productos.profile') }}" class="nav-link font-weight-bold text-white">
            Gestion Productos
          </a>
        </li>
        <li class="nav-item">
          <a href="getPedidos" class="nav-link font-weight-bold text-white">
            Pedidos
          </a>
        </li>
        <li class="nav-item">
          <a href="getEnvios" class="nav-link font-weight-bold text-white">
            Envios
          </a>
        </li>
        <li class="nav-item">
          <a href="getfinanzas" class="nav-link font-weight-bold text-white">
            Finanzas
          </a>
        </li>
        {% else %}

        <li class="nav-item">
          <a href="{{ url_for('productos.profile') }}" class="nav-link font-weight-bold text-white">
            Perfil de Usuario
          </a>
        </li>

        <li class="nav-item">
          <a href="{{ url_for('productos.productosMenu') }}" class="nav-link font-weight-bold text-white">
            Menu
          </a>
        </li>

        {% endif %}

        {% endif %}

        {% if not current_user.is_authenticated %}

        <li class="nav-item">
          <a href="{{ url_for('auth.login') }}" class="nav-link  text-white">
            Inicio de Sesion
          </a>

        </li>
        <li class="nav-item">
          <a href="{{ url_for('auth.register') }}" class="nav-link  text-white">
            Registro
          </a>

        </li>
        {% endif %}

      </ul>
      {% if current_user.is_authenticated %}
      <ul class="navbar-nav flex-row ml-md-auto d-none d-md-flex">
        {% if not admin %}
        <button type="button" style="background-color: #4abaa5; right: 0;" class="btn text-white" data-toggle="popover"
          data-placement="bottom" title=" Cesta " data-content="This is the content of my popover."><i
            class="bi bi-cart-dash"></i></button>
        {% endif %}

        <li class="nav-item">
          <a href="{{ url_for('auth.logout') }}" class="nav-link font-weight-bold text-white">
            <i class="bi bi-box-arrow-right"></i>
          </a>
        </li>
      </ul>


      {% endif %}
    </div>
  </nav>

  <div class="container">
    {% block content %}
    {% endblock %}
    <div style="margin-top: 15px;">
      
    </div>
  </div>

  <script>
    $(document).ready(function () {
      $('#example').DataTable({
        pagingType: 'full_numbers',
        pageLength: 5,
        lengthMenu: [[5, 10, 20, -1], [5, 10, 20, 'Todos']],
          language: {
          "decimal": "",
          "emptyTable": "No hay información",
          "info": "Mostrando _START_ a _END_ de _TOTAL_ Entradas",
          "infoEmpty": "Mostrando 0 to 0 of 0 Entradas",
          "infoFiltered": "(Filtrado de _MAX_ total entradas)",
          "infoPostFix": "",
          "thousands": ",",
          "lengthMenu": "Mostrar _MENU_ Entradas",
          "loadingRecords": "Cargando...",
          "processing": "Procesando...",
          "search": "Buscar:",
          "zeroRecords": "Sin resultados encontrados",
          "paginate": {
            "first": "Primero",
            "last": "Ultimo",
            "next": "Siguiente",
            "previous": "Anterior"
          }
        }
      });
    });

    $(function () {
      $('[data-toggle="popover"]').popover()
    })

  </script>

  <script src="https://cdn.datatables.net/v/dt/dt-1.13.4/datatables.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
  <script src="../static/js/alertas.js"></script>
  <script src="../static/js/pedidos.js"></script>
  <script src="../static/js/envios.js"></script>

</body>

</html>

templates/carrousel.html
{% extends "base.html" %}

{% block content %}

<div id="carouselExampleIndicators" class="carousel slide mb-4 fade-in" data-ride="carousel">
    <ol class="carousel-indicators">
        {% for producto in informativo %}
        <li data-target="#carouselExampleIndicators" data-slide-to="{{ loop.index0 }}" {% if loop.first %} class="active" {% endif %}></li>
        {% endfor %}
    </ol>
    <div class="carousel-inner">
        {% for producto in informativo %}
        <div class="carousel-item {% if loop.first %} active {% endif %}">
            <div class="card mb-3 carousel-card">
                <div class="row no-gutters">
                    <div class="col-md-7">
                        <div class="card-body">
                            <h2 class="card-title">{{ producto.nombre }}</h2>
                            <p class="card-text">{{ producto.descripcion }}</p>
                            <p class="card-text"><strong>Stock:</strong> {{ producto.stock }}</p>
                            <p class="card-text"><strong>Altura:</strong> {{ producto.altura }}</p>
                            <p class="card-text"><strong>Ancho:</strong> {{ producto.ancho }}</p>
                            <p class="card-text"><strong>Largo:</strong> {{ producto.largo }}</p>
                        </div>
                    </div>
                    <div class="col-md-5 d-flex align-items-center">
                        <img class="card-img w-100" src="../static/img/InflabAcuatico.jpg" alt="Imagen de {{ producto.nombre }}">
                        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="sr-only">Previous</span>
                        </a>
                        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="sr-only">Next</span>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    
    
</div>
<div class="container fade-in" >
    <div class="row">
        {% for producto in informativo %}
        <div class="col-md-4">
            <div class="card mb-4 box-shadow" data-aos="flip-left">
                <img class="card-img w-100" src="../static/img/InflabAcuatico.jpg" alt="Imagen de {{ producto.nombre }}">
                <div class="card-body">
                    <h3 class="card-title">{{ producto.nombre }}</h3>
                    <p class="card-text">{{ producto.descripcion }}</p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <a type="button" class="btn text-white btn-warning ml-3" href="{{ url_for('informativo.login') }}"><i class="bi bi-cart-dash bi-fw"></i> Añadir</a>

                            <a type="button" class="btn btn-outline-secondary ver-detalles" href="{{ url_for('informativo.ver_detalle', id=producto.id) }}">Ver detalles</a>
                        </div>
                        
                          
                        
                        <small class="text-muted">{{ producto.precio }}</small>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

templates/contacto.html
{% extends "base.html" %} 

{% block content %}
<!--Section: Contact v.2-->
<section class="mb-4">

    <!--Section heading-->
    <h2 class="h1-responsive font-weight-bold text-center my-4 fade-in">Contactanos</h2>
    <!--Section description-->
    <p class="text-center w-responsive mx-auto mb-5 fade-in">¿Tienes alguna duda o sugerencia?, no dudes en contactarnos estamos disponibles 24/7 para ti.</p>

    <div class="row">

        <!--Grid column-->
        <div class="col-md-9 mb-md-0 mb-5 fade-in-left">
            <form id="contact-form" name="contact-form" action="mail.php" method="POST">

                <!--Grid row-->
                <div class="row">

                    <!--Grid column-->
                    <div class="col-md-6">
                        <div class="md-form mb-0">
                            <label for="name" class="">Nombre</label>

                            <input type="text" id="name" name="name" class="form-control">
                        </div>
                    </div>
                    <!--Grid column-->

                    <!--Grid column-->
                    <div class="col-md-6">
                        <div class="md-form mb-0">
                            <label for="email" class="">Correo Electronico</label>

                            <input type="text" id="email" name="email" class="form-control">
                        </div>
                    </div>
                    <!--Grid column-->

                </div>
                <!--Grid row-->

                <!--Grid row-->
                <div class="row">
                    <div class="col-md-12">
                        <div class="md-form mb-0">
                            <label for="subject" class="">Asunto</label>

                            <input type="text" id="subject" name="subject" class="form-control">
                        </div>
                    </div>
                </div>
                <!--Grid row-->

                <!--Grid row-->
                <div class="row mt-4">

                    <!--Grid column-->
                    <div class="col-md-12">

                        <div class="md-form">
                            <textarea type="text" id="message" name="message" rows="2" class="form-control md-textarea"></textarea>
                            <label for="message">Mensaje</label>
                        </div>

                    </div>
                </div>
                <!--Grid row-->

            </form>

            <a class="btn btn-outline-warning fade-in">Enviar</a>
        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-3 text-center fade-in-right">
            <ul class="list-unstyled mb-0">
                <li><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-geo-alt-fill" viewBox="0 0 16 16">
                    <path d="M8 16s6-5.686 6-10A6 6 0 0 0 2 6c0 4.314 6 10 6 10zm0-7a3 3 0 1 1 0-6 3 3 0 0 1 0 6z"/>
                  </svg>
                    <p>León de los Aldama, GTO 40882, MX</p>
                </li>

                <li><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-envelope-fill" viewBox="0 0 16 16">
                    <path d="M0 3a1 1 0 0 1 1-1h14a1 1 0 0 1 1 1v10a1 1 0 0 1-1 1H1a1 1 0 0 1-1-1V3zm1.217 1L8 8.23 14.783 4H1.217zm-.844 1.678L8 9.77l6.627-4.093c.146.335.251.692.316 1.065L8 11.77 1.7 6.743c.064-.373.17-.73.316-1.065z"/>
                    </svg>
                    <p>example@example.com</p>
                    </li>            <li><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-phone-fill" viewBox="0 0 16 16">
                        <path d="M10.879 3.636a1 1 0 0 1 .492 1.32l-1.931 3.54a1 1 0 0 1-.836.504l-2.28.228a11.238 11.238 0 0 1-3.403-.778 11.238 11.238 0 0 1-3.403.778l-2.28-.228a1 1 0 0 1-.836-.504l-1.931-3.54a1 1 0 0 1 .492-1.32l1.74-.992a12.237 12.237 0 0 1 5.692-1.22 12.237 12.237 0 0 1 5.692 1.22l1.74.992zM4.144 2.372L2.403 3.364a1 1 0 0 1-.492 1.32l-.925.529 1.47 2.705.925-.529a1 1 0 0 1 1.04 0l1.47 2.705.925-.529a1 1 0 0 1 1.04 0l.925.529 1.47-2.705-.925-.529a1 1 0 0 1-.492-1.32l1.74-.992a10.237 10.237 0 0 0-4.784-1.02 10.237 10.237 0 0 0-4.784 1.02l1.74.992z"/>
                      </svg>
                        <p>+52 1 123456789</p>
                    </li>
                </ul>
            </div>
            <!--Grid column-->
        
          </div>
          <!--Grid row-->
        </div>
    </section>
    
{% endblock %}        

templates/home.html
<h1 class="mt-3 display-3 text-center fade-in">InflabExpress</h1>
<div id="carouselExampleIndicators" class="carousel slide mb-4 fade-in" data-ride="carousel">
  <ol class="carousel-indicators">
      <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
      <div class="carousel-item active fade-in-left">
          <img class="d-block w-100" src="../static/img/inflable1.jpg" alt="First slide">
      </div>
      <div class="carousel-item fade-in-left">
          <img class="d-block w-100" src="../static/img/inflable2.jpg" alt="Second slide">
      </div>
      <div class="carousel-item fade-in-left">
          <img class="d-block w-100" src="../static/img/inflable3.jpg" alt="Third slide">
      </div>
      <div class="carousel-item fade-in-left">
        <img class="d-block w-100" src="../static/img/inflable4.jpg" alt="Fourth slide">
      </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
  </a>
</div>
<h3 class="text-center fade-in-right">Tu tienda de inflables al por mayor favorita</h3>
<style>
    .hidden {
      display: none;
    }
  
    .visible {
      display: block;
    }
  </style>
  
  <div class="row justify-content-center">
    <div class="mb-5 col-1.5 carousel-card fade-in-left d-flex justify-content-center align-items-center position-relative">
      <img src="../static/img/inflable_muestra.jpg" class="card-img-top" alt="Inflables" style="max-width: 200px; height: auto;">
      <h5 class="text-center text-white p-4 hidden" style="position: absolute; bottom: 0; background-color: #f5c754b2; width: 100%;">Los mejores inflables para tus eventos, ¡compra ya y diviértete al máximo!</h5>
    </div>
  
    <div class="mb-5 col-9" style="background-color: #f5c754b2;">
      <h5 class="text-center text-white p-5 fade-in-right">Somos una empresa de fabricación de inflables, nuestro trabajo representa la calidad de nuestros productos, ven y conócenos.</h5>
    </div>
  </div>
  
  
  <script>
    const img = document.querySelector(".carousel-card img");
const h5 = document.querySelector(".carousel-card h5");

let timer;

img.addEventListener("mouseenter", () => {
  clearTimeout(timer);
  h5.classList.remove("hidden");
  h5.classList.add("visible");
});

img.addEventListener("mouseleave", () => {
  timer = setTimeout(() => {
    h5.classList.remove("visible");
    h5.classList.add("hidden");
  }, 2000);
});

  </script>
  

templates/index.html
{% extends "base.html" %}
{% block content %}
{% include "home.html" %}
{% endblock %}

templates/sobre_nosotros.html
{% extends "base.html" %} 
{% block content%}
<!-- Encabezado -->
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4 fade-in">Sobre nosotros</h1>
    <p class="lead fade-in text-justify">InflabExpress es una empresa dedicada a la producción y venta de inflables para eventos y fiestas infantiles. Fundada en [año de fundación], la empresa se ha enfocado en ofrecer productos de alta calidad y durabilidad a sus clientes. A pesar de su corta trayectoria, InflabExpress se ha consolidado en el mercado gracias a su compromiso con la excelencia y su atención al cliente.</p>
  </div>
</div>

<!-- Contenido -->
<div class="container">
  <div class="row">
    <div class="col-md-6 fade-in-left">
      <h2>Nuestra misión</h2>
      <p class="text-justify">En InflabExpress, nuestra misión es ofrecer productos de alta calidad y durabilidad para satisfacer las necesidades de nuestros clientes en eventos y fiestas infantiles. Nos esforzamos por superar las expectativas de nuestros clientes mediante la mejora continua de nuestros procesos de producción y atención al cliente.</p>

    </div>
    <div class="col-md-6 fade-in-left">
      <h2>Nuestros valores</h2>
      <ul class="text-justify">
        <li class="fade-in">Innovación</li>
        <li class="fade-in">Calidad</li>
        <li class="fade-in">Compromiso</li>
        <li class="fade-in">Trabajo en equipo</li>
        <li class="fade-in">Excelencia</li>
      </ul>
    </div>
    <div class="col-md-6 fade-in-right">
      <h2>Nuestro equipo</h2>
      <p class="text-justify">En InflabExpress, contamos con un equipo de profesionales comprometidos con la calidad y la excelencia en todo lo que hacemos. Nuestro equipo de producción está altamente capacitado en la fabricación de inflables de alta calidad y durabilidad, y nuestro equipo de atención al cliente está dedicado a ofrecer un servicio excepcional a nuestros clientes. Además, contamos con un equipo de gestión que se encarga de supervisar y mejorar continuamente nuestros procesos de producción y atención al cliente para garantizar la satisfacción de nuestros clientes.</p>
      
    </div>
  </div>
</div>

{% endblock %}

templates/ver_detalle.html
{% extends "base.html" %}

{% block content %}

<div class="container fade-in">
    <div class="row">
        <div class="col-md-6">
            <h2>{{ producto.nombre }}</h2>
            <p>{{ producto.descripcion }}</p>
            <p><strong>Altura:</strong> {{ producto.altura }}</p>
            <p><strong>Ancho:</strong> {{ producto.ancho }}</p>
            <p><strong>Largo:</strong> {{ producto.largo }}</p>
            <p><strong>Stock:</strong> {{ producto.stock }}</p>
            <p><strong>Precio:</strong> {{ producto.total }}</p>
            <a type="button" onclick="window.history.back();" class="btn btn-secondary">Volver</a>
        </div>
        <div class="col-md-6 text-center">
            <img class="card-img img-thumbnail mx-auto" src="../static/img/InflabAcuatico.jpg" alt="Imagen de {{ producto.nombre }}" width="auto" , height="auto">
        </div>
    </div>
</div>


{% endblock %}